version: '3.8'

services:
  app:
    build: ./
    container_name: rmg-courses-webapi
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/rmg_courses_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.MySQL57Dialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    ports:
      - '18080:8080'
    volumes:
      - ./.docker/storage:/app/storage
    networks:
      - app-network
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: rmg-courses-db
    restart: always
    tty: true
    ports:
      - '13306:3306'
    environment:
      MYSQL_DATABASE: rmg_courses_db
      MYSQL_ROOT_PASSWORD: root
      MSYQL_USER: root
    networks:
      - app-network
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
networks:
  app-network:
    driver: bridge